export const TRACK_EXPENSE = "TRACK_EXPENSE";
export const LOAD_EXPENSES = "LOAD_EXPENSES";

export const TRACK_EXPENSE_SUCCESS = "TRACK_EXPENSE_SUCCESS";
export const LOAD_EXPENSES_SUCCESS = "LOAD_EXPENSES_SUCCESS";
export const LOAD_EXPENSES_ERROR = "LOAD_EXPENSES_ERROR";
